version: '2'

networks:
  chef:
    driver: bridge

services:
  ws:
    image: codespaces/chef-ws:v0.1.0
    ports:
      - "8000:8000"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    network_mode: host
    networks:
      - chef
    container_name: ws
    domainname: codespaces.io
    hostname: ws
    restart: always

  node1:
    image: codespaces/chef-node-centos-6:v0.1.0
    ports:
       - "83:80"
    networks:
      - chef
    container_name: node1
    domainname: codespaces.io
    hostname: node1
    restart: always

  node2:
    image: codespaces/chef-node-centos-6:v0.1.0
    ports:
       - "81:80"
    networks:
      - chef
    container_name: node2
    domainname: codespaces.io
    hostname: node2
    restart: always

  node3:
    image: codespaces/chef-node-centos-6:v0.1.0
    ports:
      - "82:80"
    networks:
      - chef
    container_name: node3
    domainname: codespaces.io
    hostname: node3
    restart: always

  node4:
    image: codespaces/chef-node-centos-6:v0.1.0
    ports:
      - "3306:3306"
    networks:
      - chef
    container_name: node4
    domainname: codespaces.io
    hostname: node4
    restart: always
